### ISSUE TITLE
Private keys should be extract from UI login.

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/proof-of-attendance#22]
Currently, our server has a hardcoded private key. We need to find a way that after user logins we can send the private key to the server. That way the server does not need to have a hardcoded private key through Environment Variables.

**Comment by mrrobot16** [comment]
Currently, our server has a hardcoded private key. We need to find a way that after user logins we can send the private key to the server. That way the server does not need to have a hardcoded private key through Environment Variables.

**Comment by RenierC** [comment]
@mrrobot16 I checked this out and found out that it was not possible to extract user's private keys, this is by Near's design.

What I found that could achieve the similar outcome are 2 different keys

1. [FullAccess Keys](https://docs.near.org/docs/concepts/account#full-access-keys): That give full access privileges
2. [Function Call Keys](https://docs.near.org/docs/concepts/account#function-call-keys): Which allow access to specified functions.

By the way the app is currently set upon login the user gets full access keys and with PR #23 you can access them

**Comment by RenierC** [comment]
@mrrobot16 Got an update on this another way to get them from the UI can be like this 

```javascript
  const private_key = window.walletConnection
    ._keyStore
    .localStorage[`near-api-js:keystore:${window.accountId}:testnet`];
```
